### ISSUE TITLE
Feature: Add temp and humidity as state_attributes

### ISSUE THREAD

**Issue by bj00rn** [Strixx76/mold_risk_index#9]
Would be nice to have the values as state attributes on MoldRiskBaseSensor for temperature and humidity for easy access.

**Comment by Strixx76** [comment]
What temperature and humidity is it that you want to see as a attribute?
Is it the current temperature and humidity, then why not just build the dashboard so that you can see the the temperature and humidity sensor right next to this value instead?
Is it the temperature and humidity that caused the risk level to change? What would be the use of that?
